sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    secure: HO41LMpMXkF2In9+1sxWVu7fgolL+y9+4Q5PI6wZX2L5pDwpPJCjxaQarQXCEnoIxED1PlP03JuF7ULNz0zw1ylYhAOfOSdkxFZRnE2wMZqq6qvXBHwyMiDrAociIzoPKSGv7JVrKPsjsnd+96K6xxueIodQZrmAdyq7N/M82Mc=
  matrix:
    - CRATE=serde_tests TARGET=test
matrix:
  include:
    - rust: nightly
      env: CRATE=serde_macros TARGET=test
    - rust: nightly
      env: CRATE=serde_macros TARGET=bench
    - rust: nightly
      env: CRATE=serde_tests TARGET=bench
script:
  - (cd $CRATE && cargo $TARGET)
after_success: |
  [ $TRAVIS_BRANCH = "master" ] &&
  [ $TRAVIS_PULL_REQUEST  = false ] &&
  mkdir -p target/doc &&
  (cd serde && cargo doc --no-deps) &&
  (cd serde_codegen && cargo doc --no-deps) &&
  (cd serde_macros && cargo doc --no-deps) &&
  (cd serde_json && cargo doc --no-deps) &&
  cp -r serde/target/doc target/doc/serde &&
  cp -r serde_codegen/target/doc target/doc/serde_codegen &&
  cp -r serde_macros/target/doc target/doc/serde_macros &&
  cp -r serde_json/target/doc target/doc/serde_json &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
