sudo: false
language: rust
cache: cargo

# run builds for all the trains (and more)
rust:
  - 1.13.0
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: nightly
      env: CLIPPY=true
  allow_failures:
    - rust: nightly
      env: CLIPPY=true
  fast_finish: true

script: ./travis.sh
