[package]
name = "serde"
version = "0.2.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]

[lib]
name = "serde"

[dependencies]
rustc-serialize = "*"

[dev-dependencies.serde_macros]
path = "serde_macros/"
