[package]
name = "serde"
version = "0.3.1"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A serialization/deserialization framework"
repository = "https://github.com/erickt/rust-serde"

[dependencies]
num = "*"

[dev-dependencies]
rustc-serialize = "*"

[dev-dependencies.serde_macros]
path = "serde_macros/"
version = "0.3.1"
