[package]
name = "serde"
version = "0.2.1"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A serialization/deserialization framework"
repository = "https://github.com/erickt/rust-serde"

[lib]
name = "serde"

[dependencies]
rustc-serialize = "*"

[dev-dependencies]
serde_macros = "0.2.1"
