[package]
name = "serde_test_suite_deps"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[workspace]

[dependencies]
serde = { path = "../../serde" }
serde_derive = { path = "../../serde_derive" }

[patch.crates-io]
proc-macro2 = { git = 'https://github.com/alexcrichton/proc-macro2', branch = 'v3' }
quote = { git = 'https://github.com/alexcrichton/quote', branch = 'v3' }
syn = { git = 'https://github.com/alexcrichton/syn', branch = 'v3' }
