[package]
name = "serde_test_suite_deps"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[dependencies]
serde = { path = "../../serde" }
serde_derive = { path = "../../serde_derive" }
