[package]
name = "serde_macros"
version = "0.2.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]

[lib]
name = "serde_macros"
plugin = true

[dependencies]
quasi = "0.1.3"
quasi_macros = "0.1.3"
aster = "0.1.3"
