[package]
name = "serde_macros"
version = "0.1.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"

[[lib]]
name = "serde_macros"
path = "src/lib.rs"
plugin = true
