[package]
name = "serde2"
version = "0.1.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]

[lib]
name = "serde2"

#[[bin]]
#name = "serde2"
#path = "src/bin.rs"

[dependencies]
rustc-serialize = "*"

[dependencies.serde2_macros]
path = "serde2_macros/"
