[package]
name = "serde_derive"
version = "0.9.1"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros 1.1 implementation of #[derive(Serialize, Deserialize)]"
homepage = "https://serde.rs"
repository = "https://github.com/serde-rs/serde"
documentation = "https://serde.rs/codegen.html"
keywords = ["serde", "serialization"]
include = ["Cargo.toml", "src/**/*.rs"]

[features]
unstable = []
unstable-testing = ["clippy"]

[badges]
travis-ci = { repository = "serde-rs/serde" }

[lib]
name = "serde_derive"
proc-macro = true

[dependencies]
clippy = { version = "0.*", optional = true }
quote = "0.3.8"
serde_codegen_internals = { version = "=0.11.3", default-features = false, path = "../serde_codegen_internals" }
syn = { version = "0.10", features = ["aster", "visit"] }

[dev-dependencies]
compiletest_rs = "0.2"
fnv = "1.0"
serde = { version = "0.9", path = "../serde" }
serde_test = { version = "0.9", path = "../serde_test" }
