[package]
name = "serde2_macros"
version = "0.1.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]

[lib]
name = "serde2_macros"
plugin = true

[dependencies]
quasi = "0.1.0"
quasi_macros = "0.1.0"
aster = "0.1.2"
